"""empty message

Revision ID: 284423eaa922
Revises: ed9bc1e79d9e
Create Date: 2025-05-07 21:38:50.854786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284423eaa922'
down_revision = 'ed9bc1e79d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=120), nullable=False),
    sa.Column('user.id', sa.Integer()),
    sa.Column('post.id', sa.Integer()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer()),
    sa.Column('enum??', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('post.id', sa.Integer()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer()),
    sa.Column('user.id', sa.Integer()),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('media')
    op.drop_table('comment')
    # ### end Alembic commands ###
