"""empty message

Revision ID: 913554159322
Revises: 013aca54c2fe
Create Date: 2025-05-08 20:14:48.840068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913554159322'
down_revision = '013aca54c2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
